### ISSUE TITLE
rename the releasename

### ISSUE THREAD

**Issue by blackcrack** [thebookisclosed/Comet#1]
Hi,

can you maybe rename the releasename maybe in future

%programname%-%releaseversion%.zip
so
comet-2019.4.15.1004.zip 

to have the possible for have a nice name and know which
release-date and version is it.. thank you :)

edit: cant stop to thinking about... 
and maybe a better name could be : 
Managed Disk Cleanup = MDC or wincleaner
Managed Disk Cleanup for Windows = MDCFW,  cleanerwinnt

a short name is maybe more better and then the architecture, like : 
mdc-x86 or for the x86 => mdc-x86
or
mdcfw-x86_x64 or for the x86_64 => mdcfw-x86_64
to named what it is..

and you have told, not older than win8 ... hm.. longterm/longshoot, 
working together maybe in Reactos...
could you maybe programming a version for reactos to have a cleaner in reactos.org ?

the whole just as a suggestion for you,
The whole thing is same undoubtedly as ingenious as the distributed 
cleanmgr+ ( https://www.getclone.app/cleanmgrplus)
project  :+1:  :smile: 

best regards
Blacky

**Comment by thebookisclosed** [comment]
Thank you for the suggestions, the naming related ones are rolled into the new release. There is however no need for architecture separation (at least at the moment). Contributing to other projects is something I'd like to do but given how time consuming such stuff can be, I can't really guarantee that.
In case you'd like to discuss things further, feel free to reach out to me on Twitter.

**Comment by blackcrack** [comment]
@thebookisclosed 
:+1: 
i don't use twitter :)

best regards
Blacky
