### ISSUE TITLE
New Icon

### ISSUE THREAD

**Issue by jebeld17** [thebookisclosed/Comet#2]
I absolutely love that this app exists to carry on a useful "Classic function" in older versions of Windows and Windows 10 that's now since been removed.
One thing I've noticed though, is that the icon doesn't seem to be anything rekated to the subject, though.
Since I've noticed that, I'd like to offer an alternative that I've designed.

Please take a look and enjoy. I hope this gets added to the program. :)
![ColorToAlpha_Tol_0 250](https://user-images.githubusercontent.com/9492083/57050487-cb8e6f80-6c4a-11e9-9a53-a3b50aca836f.png)

See full archive with extra variants and .XCF working file:
[Final Comet Icon.zip](https://github.com/thebookisclosed/Comet/files/3136353/Final.Comet.Icon.zip)

**Comment by jebeld17** [comment]
See Pull Request Number 3 at https://github.com/thebookisclosed/Comet/pull/3

**Comment by thebookisclosed** [comment]
Thank you for the suggestion but I disagree that the app's icon is unrelated to the subject. It's a disk, with a file, with a red X signifying file deletion. With this icon being introduced only a few releases ago, I have no intentions of changing it.
