### ISSUE TITLE
Better System UI Integration by Utilizing XAML Islands

### ISSUE THREAD

**Issue by jebeld17** [thebookisclosed/Comet#4]
With Microsoft now allowing standard Win32 and other non-UWP apps to access Fluent Design (UWP) design resources by utilizing XAML and XAML Islands, this is a great opportunity to bring Comet Disk Cleanup into the new age of design philosophy, all without limiting application functionality or completely redesigning it.

Attached, I've included a XAML design set (in .txt and .json format -- open the attached ZIP) that can potentially be utilized by Comet Disk Cleanup in a future release.
[Default.zip](https://github.com/thebookisclosed/Comet/files/3144651/Default.zip)
[Default.txt](https://github.com/thebookisclosed/Comet/files/3144652/Default.txt)

**Comment by jebeld17** [comment]
_**.txt contents:**_

`
<ResourceDictionary.ThemeDictionaries>
    <ResourceDictionary x:Key="Default">
        <ResourceDictionary.MergedDictionaries>
            <ColorPaletteResources Accent="#FF0073CF" AltHigh="#FF000000" AltLow="#FF000000" AltMedium="#FF000000" AltMediumHigh="#FF000000" AltMediumLow="#FF000000" BaseHigh="#FFFFFFFF" BaseLow="#FF333333" BaseMedium="#FF9A9A9A" BaseMediumHigh="#FFB4B4B4" BaseMediumLow="#FF676767" ChromeAltLow="#FFB4B4B4" ChromeBlackHigh="#FF000000" ChromeBlackLow="#FFB4B4B4" ChromeBlackMedium="#FF000000" ChromeBlackMediumLow="#FF000000" ChromeDisabledHigh="#FF333333" ChromeDisabledLow="#FF9A9A9A" ChromeGray="#FF808080" ChromeHigh="#FF808080" ChromeLow="#FF151515" ChromeMedium="#FF1D1D1D" ChromeMediumLow="#FF2C2C2C" ChromeWhite="#FFFFFFFF" ListLow="#FF1D1D1D" ListMedium="#FF333333" />
            <ResourceDictionary>
                <Color x:Key="SystemChromeAltMediumHighColor">#CC000000</Color>
                <Color x:Key="SystemChromeAltHighColor">#FF000000</Color>
                <Color x:Key="SystemRevealListLowColor">#FF1D1D1D</Color>
                <Color x:Key="SystemRevealListMediumColor">#FF333333</Color>
                <Color x:Key="RegionColor">#FF000000</Color>
                <SolidColorBrush x:Key="RegionBrush" Color="{StaticResource RegionColor}" />
            </ResourceDictionary>
        </ResourceDictionary.MergedDictionaries>
    </ResourceDictionary>
    <ResourceDictionary x:Key="Light">
        <ResourceDictionary.MergedDictionaries>
            <ColorPaletteResources Accent="#FF0073CF" AltHigh="#FFFFFFFF" AltLow="#FFFFFFFF" AltMedium="#FFFFFFFF" AltMediumHigh="#FFFFFFFF" AltMediumLow="#FFFFFFFF" BaseHigh="#FF000000" BaseLow="#FFCCCCCC" BaseMedium="#FF898989" BaseMediumHigh="#FF5D5D5D" BaseMediumLow="#FF737373" ChromeAltLow="#FF5D5D5D" ChromeBlackHigh="#FF000000" ChromeBlackLow="#FFCCCCCC" ChromeBlackMedium="#FF5D5D5D" ChromeBlackMediumLow="#FF898989" ChromeDisabledHigh="#FFCCCCCC" ChromeDisabledLow="#FF898989" ChromeGray="#FF737373" ChromeHigh="#FFCCCCCC" ChromeLow="#FFECECEC" ChromeMedium="#FFE6E6E6" ChromeMediumLow="#FFECECEC" ChromeWhite="#FFFFFFFF" ListLow="#FFE6E6E6" ListMedium="#FFCCCCCC" />
            <ResourceDictionary>
                <Color x:Key="SystemChromeAltMediumHighColor">#CCFFFFFF</Color>
                <Color x:Key="SystemChromeAltHighColor">#FFFFFFFF</Color>
                <Color x:Key="SystemRevealListLowColor">#FFE6E6E6</Color>
                <Color x:Key="SystemRevealListMediumColor">#FFCCCCCC</Color>
                <RevealBackgroundBrush x:Key="SystemControlHighlightListLowRevealBackgroundBrush" TargetTheme="Light" Color="{ThemeResource SystemRevealListMediumColor}" FallbackColor="{ StaticResource SystemListMediumColor}" />
                <Color x:Key="RegionColor">#FFFFFFFF</Color>
                <SolidColorBrush x:Key="RegionBrush" Color="{StaticResource RegionColor}" />
            </ResourceDictionary>
        </ResourceDictionary.MergedDictionaries>
    </ResourceDictionary>
    <ResourceDictionary x:Key="HighContrast">
        <StaticResource x:Key="RegionColor" ResourceKey="SystemColorWindowColor" />
        <SolidColorBrush x:Key="RegionBrush" Color="{StaticResource RegionColor}" />
    </ResourceDictionary>
</ResourceDictionary.ThemeDictionaries>
`

**Comment by thebookisclosed** [comment]
I'm sorry but I don't understand where you're going with these suggestions. Adopting XAML Islands means **drastically** reducing the compatibility scope of the project, from Windows Vista+ to Windows 10 1809+. Additionally, there is no need for Resource Dictionaries like this one (which contains the default colors) to make use of Islands.
