### ISSUE TITLE
[Idea] [Suggestion] Merge with Microsoft PowerToys 2019

### ISSUE THREAD

**Issue by jebeld17** [thebookisclosed/Comet#5]
With Microsoft Powertoys (2019) just announced and 100% open-source, this could be a great time to bring Disk Cleanup back for good as Comet, a modern Disk Cleanup app with a Classic look and feel.

Just an idea. Take a look at the source code here:
https://github.com/microsoft/PowerToys

**Comment by vartaxe** [comment]
Yes we need this :)

**Comment by thebookisclosed** [comment]
This is not an idea I will be considering for now, the issue may be reopened later but I wouldn't hold your breath
