### ISSUE TITLE
Adding additional cleanup locations

### ISSUE THREAD

**Issue by PCAssistSoftware** [thebookisclosed/Comet#7]
Hi

Really like what you have done here, and would love to be able to contribute to the project.  I love the idea about being able to add additional cleanup locations by way of ini files or similar, but can't see how this can easily be done, perhaps if you have time then give a quick overview of the process and then myself (and others) can start supplying .ini files (or similar) with cleanup information for many other areas.

Thanks

**Comment by thebookisclosed** [comment]
This functionality is not within the scope of the project.
Comet only works with registered Disk Cleanup handlers and doesn't contain any custom file deletion/cleanup code.
If you still wish to have a cleanup handler light up in Comet (and by proxy Disk Cleanup and modern Storage settings) you'll have to write your own handler that implements IEmptyVolumeCache and register it in the registry.

**Comment by PCAssistSoftware** [comment]
Okay many thanks for your response

I had actually been playing about with exactly what you suggest this morning and have succesfully added my own entries to HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\VolumeCaches and they work fine

Thanks again
